version: "3.3"
services:
    mongodb:
        container_name: poynt
        image: mongo:latest
        restart: unless-stopped
        volumes:
            - ./db:/data/db
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}